INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3231, 'NEW YORK TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3232, 'FLEC RR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3233, 'FLORIDA EAST COAST RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3234, 'TRANSIT SOLUTIONS GROUP');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3235, 'UNION PACIFIC RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3236, 'AMTRAK');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3237, 'BNSF');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3238, 'METRA');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3239, 'BNSF RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3240, 'CSX RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3241, 'NORFOLK SOUTHERN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3242, 'FLORIDA DISPATCH CO/EAST COAST RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3243, 'UNION PACIFIC');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3244, 'NEW JERSEY TRANSIT RAIL OPERATIONS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3245, 'METRA COMMUTER RAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3246, 'SOUND TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3247, 'CONRAIL LINE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3248, 'LITTLE ROCK AND WESTERN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3249, 'NYC TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3250, 'METRO LINK');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3251, 'CSX');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3252, 'NEW MEXICO RAIL RUNNER');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3253, 'NM RAIL RUNNER EXPRESS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3254, 'BNSF RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3255, 'Unknown');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3256, 'NONE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3257, 'PANAM RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3258, 'UTAH TRANSIT AUTHORITY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3259, 'SOUTH FLORIDA REGIONAL TRANSPORT AUTH');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3260, 'RTDC');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3261, 'ADVANSIX');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3262, 'NJ TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3263, 'NEW JERSEY TRANSIT RAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3264, 'PATH RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3265, 'LONG ISLAND RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3266, 'CANADIAN NATIONAL RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3267, 'NY CITY TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3268, 'CANADIAN PACIFIC RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3269, 'METROPOLITAN TRANSIT AUTHORITY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3270, 'PROVIDENCE AND WORCESTER');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3271, 'NORTH COUNTY TRANSIT DISTRICT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3272, 'KEOLIS COMMUTER SERVICES');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3273, 'NYC TRANSIT (SUBWAY)');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3274, 'TRINITY RAILWAY EXPRESS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3275, 'METROLINK');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3276, 'KANSAS CITY SOUTHERN RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3277, 'STILLWATER CENTRAL RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3278, 'NEW YORK CITY TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3279, 'RED RIVER VALLEY AND WESTERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3280, 'CALTRAIN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3281, 'ALSTOM / SUN RAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3282, 'FDOT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3283, 'ALBANY PORT RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3284, 'RAPID CITY PIERRE AND EASTERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3285, 'CONRAIL CONSOLIDATED RAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3286, 'NY SUSQUEHANNA & WESTERN RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3287, 'N/A');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3288, 'GENNESEE AND WYOMING RAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3289, 'CN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3290, 'DELTA PETROCHEMICAL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3291, 'SONOMA MARIN AREA RAIL TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3292, 'BAY LINE RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3293, 'NO TRAINS INVOLVED');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3294, 'BURLINGTON NORTHERN SANTA FE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3295, 'LAKE STATE RAILWAY COMPANY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3296, 'HOUSTON METROPOLITAN TRANSIT AUTHORITY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3297, 'METRA RAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3298, 'MBTA');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3299, 'EAST COAST RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3300, 'INDIANA HARBOR RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3301, 'SACRAMENTO REGIONAL TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3302, 'EAST COAST RAIL ROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3303, 'SEPTA');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3304, 'BRIGHTLINE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3305, 'CSX RAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3306, 'BELT RAILWAY POLICE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3307, 'SAN FRANCISCO BAY AREA RAPID TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3308, 'TNHR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3309, 'NEW YORK CITY TRANSIT AUTHORITY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3310, 'AUX SABLE LIQUID PRODUCT LP');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3311, 'MARQUETTE RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3312, 'MARYLAND TRANSIT AUTHORITY (MTA)');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3313, 'SONOMA MARIN RAIL AND TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3314, 'CONSOLIDATED RAIL CORPORATION');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3315, 'EVANSVILLE WESTERN RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3316, 'CANADIAN NATIONAL RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3317, 'GEORGIA SW RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3318, 'UTA UFRC TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3319, 'PRIVATE TRACK');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3320, 'ALTAMONT CORRIDOR EXPRESS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3321, 'TOLEDO REFINING COMPANY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3322, 'NASHVILLE EASTERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3323, 'ARIZONA AND CALIFORNIA RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3324, 'CHICAGO TRANSIT AUTHORITY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3325, 'BRIGHTLINE FLORIDA');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3326, 'KEOLIS COMMUTER SERVICE /MBTA');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3327, 'TEXAS AND NEW MEXICO RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3328, 'CLEVELAND CLIFFS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3329, 'WISCONSIN CENTRAL RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3330, 'UTAH TRANSIT AUTHORITY -COMMUTER RAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3331, 'SUNRAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3332, 'CAPITOL METRO RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3333, 'ALTAMONT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3334, 'CHARLOTTE AREA TRANSIT SYSTEM');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3335, 'AMERICAN RAIL DISPATCH CENTER');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3336, 'TRANSIT AMERICA SERVICES');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3337, 'UTAH TRANSIT AUTHORITY (UTAX)');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3338, 'THE ALABAMA GULFCOAST RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3339, 'MERIDIAN AND BIGBEE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3340, 'CONNECTICUT SOUTHERN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3341, 'CSXRAIL ROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3342, 'CONRAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3343, 'PORTLAND AND WESTERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3344, 'GENESSEE RAILROAD SERVICES');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3345, 'CERTAIN TEED');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3346, 'CANADIAN PACIFIC RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3347, 'ASTA');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3348, 'TERMINAL RAILWAY / AL STATE PORT AUTHORI');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3349, 'ASARCO');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3350, 'PORT TERMINAL RAILROAD ASSOCIATION');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3351, 'UNIVAR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3352, 'UTA FRONTRUNNER (UFRC)');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3353, 'BUFFALO PITTSBURG RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3354, 'ARKANSAS & MISSOURI RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3355, 'METRA PASSENGER TRAIN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3356, 'MARC TRAIN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3357, 'PALOUSE RIVER & COULEE CITY RR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3358, 'SAN DIEGO TROLLEY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3359, 'PRIVATE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3360, 'SANTA CLARA VALLEY TRANSPORTATION AUTHOR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3361, 'METRA RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3362, 'CANADIAN PACIFIC');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3363, 'COOS BAY RAIL LINE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3364, 'KANSAS CITY SOUTHERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3365, 'ST PAUL AND PACIFIC NORTHWEST RAIL ROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3366, 'RIVERLINE (NJ TRANSIT)');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3367, 'DENVER TRANSIT OPERATORS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3368, 'CARBIDE INDUSTRIES');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3369, 'KC TERMINAL RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3370, 'METRO-NORTH RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3371, 'WESTLAKE CHEMICALS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3372, 'NORTHWEST RAILWAY MUSEUM');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3373, 'GENESEE &WYOMING RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3374, 'ALSTOM / SUNRAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3375, 'FLORIDA EAST COAST RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3376, 'METRO TRANSIT MINNEAPOLIS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3377, 'AUSTIN WESTER');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3378, 'GEORGIA PACIFIC');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3379, 'TX NORTHEASTERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3380, 'ALASKA RR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3381, 'PENNSYLVANIA NORTHEASTERN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3382, 'SAN FRANCISCO MUNICIPAL TRANSIT AGENCY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3383, 'TEXAS MATERIALS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3384, 'WATCO');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3385, 'HILTON AND ALBANY RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3386, 'RINGNECK AND WESTERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3387, 'CANADIAN NATIONAL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3388, 'GRAND ELK RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3389, 'SAN FRANCISCO BART');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3390, 'DART');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3391, 'TRIRAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3392, 'NORFOLK SOUTHER');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3393, 'PACIFIC HARBOR LINE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3394, 'KANSAS CITY SOUTHERN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3395, 'NEW YORK AND ATLANTIC RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3396, 'NEW YORK SUSQUEHANNA AND WESTERN RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3397, 'DALLAS-GARLAND AND NORTHEASTERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3398, 'AUSTIN WESTERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3399, 'PEMEX');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3400, 'IOWA INTERSTATE RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3401, 'NY TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3402, 'STILLWATER CENTRAL RR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3403, 'VELOCITY RAIL SOLUTIONS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3404, 'KIAMICHI RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3405, 'REAGENT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3406, 'GREAT LAKES CENTRAL RR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3407, 'GEORGIA SOUTHWESTERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3408, 'HOCKING VALLEY SCENIC RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3409, 'DEQUEEN & EASTERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3410, 'VRE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3411, 'UNK');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3412, 'KCS- KANSAS CITY SOUTHERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3413, 'NO TRAIN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3414, 'METRO NORTH RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3415, 'TX CITY TERMINAL RAILWAY CO / (TCT)');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3416, 'AMNTRAK');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3417, 'METRO RAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3418, 'IOWA NORTHEN RAILWAY COMPANY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3419, 'NO TRAIN INVOLVED');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3420, 'UTAH TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3421, 'CY-FAIR VOLUNTEER FIRE DEPT.');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3422, 'FINGERLAKE RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3423, 'LONG ISLAND RR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3424, 'BRIGHT LINE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3425, 'DALLAS AREA RAPID TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3426, 'SOUTH KANSAS OKLAHOMA RR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3427, 'MARYLAND MIDLAND RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3428, 'LORAM MAINTENANCE OF WAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3429, 'NYC TRANSIT AUTHORITY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3430, 'WESTERN RAILWAY MUSEUM');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3431, 'AM/NS CALVERT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3432, 'NORFOLK SOUTHERN RAILROAD 1');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3433, 'NORFOLK SOUTHERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3434, 'SAN JOAQUIN VALLEY RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3435, 'TRIMET');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3436, 'NO TRAIN INVOVLED');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3437, 'NEW HAMPSHIRE NORTHCOAST CORP');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3438, 'BURLINGTON NORTHERN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3439, 'TEXRAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3440, 'BRIGHTLINE RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3441, 'METRO TRANSIT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3442, 'INDIANA HARBOR BELT RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3443, 'COLONIAL TERMINALS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3444, 'BUFFALO SOUTHERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3445, 'UTAX');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3446, 'PORT AUTHORITY TRANSIT CORP.');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3447, 'UNION PACFIC RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3448, 'OTHER');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3449, 'PILKINGTON NORTH AMERICA');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3450, 'CARBON COUNTY EMA');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3451, 'BRIGHTLINE FL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3452, 'BUCKINGHAM BRANCH RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3453, 'MPRR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3454, 'CSXT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3455, 'UNION TANK CAR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3456, 'EASTERN IDAHO RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3457, 'WATCO COMPANIES');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3458, 'AMTAK');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3459, 'FORTH WORTH WESTERN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3460, 'IOWA INTERSTATE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3461, 'GLEN CROP');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3462, 'PSC GROUP');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3463, 'CLARK DALE CENTRAL ARIZONA RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3464, 'KEOLIS COMMUTER RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3465, 'SOUTH CENTRAL FLORIDA EXPRESS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3466, 'TACOMA RAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3467, 'NEW ORLEANS GULF COAST');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3468, 'NEW ORLEANS AND GULF COAST RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3469, 'KEOLIS TRAIN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3470, 'S.E.P.T.A.');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3471, 'CANADIAN PACIFIC RAILWAYS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3472, 'ACE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3473, 'MTA');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3474, 'AUSTIN WESTERN RR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3475, 'GARGILL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3476, 'LOND ISLAND RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3477, 'GRENDA RR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3478, 'SFMTA');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3479, 'PORT AUTHORITY TRANSIT CORP');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3480, 'ITAFOS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3481, 'LOUISVILLE & INDIANA RAILROAD CO');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3482, 'HOUSTON METROPOLITAN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3483, 'SOUTH CENTRAL FLORIDA EXPRESS INC');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3484, 'TRI MET');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3485, 'NUTRIEN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3486, 'NUTRIENT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3487, 'RAPID CITY PIERRE & EASTERN RR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3488, 'VIRGINIA RAILWAY EXPRESS');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3489, 'METROPOLITAN TRANSIT SYSTEM');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3490, 'METRA TRAIN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3491, 'MBTA COMMUTER RAIL');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3492, 'MINNESOTA COMMERCIAL RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3493, 'CFRC CENTRAL FLORIDA RAILROAD CORRIDOR');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3494, 'PORT AUTHORITY TRANS-HUDSON CORP');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3495, 'MD TRANSIT ADMIN.');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3496, 'ALTON SOUTHERN RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3497, 'UNKOWN');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3498, 'RAIL LINK');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3499, 'PORT OF GALVESTON POLICE DEPT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3500, 'GENESEE WYOMING');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3501, 'CANADIAN NATONAL RAILWAY');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3502, 'Valid Fixed Railroad');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3503, 'RAILROAD NON-RELEASE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3504, 'MOBILE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3505, 'PIPELINE');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3506, 'Valid Railroad Name');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3507, 'Valid Vessel Name');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3508, 'STORAGE TANK');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3509, 'RAILROAD');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3510, 'AIRCRAFT');
INSERT INTO [railroad] ([railroad_id], [railroad_name]) VALUES (3511, 'PLATFORM');
